version: '3'
services:
  ajax:
    image: node:latest
    user: node
    working_dir: /var/www
    command: npm -q start
    ports:
      - '8001:3000'
    volumes:
      - ./chat-ajax:/var/www
      - ./components:/var/www/components
      - ./package.json:/var/www/package.json

  websockets:
    image: node:latest
    user: node
    working_dir: /var/www
    command: npm -q start
    ports:
      - '8002:3000'
      - '3002:3001'
    volumes:
      - ./chat-websockets:/var/www
      - ./components:/var/www/components
      - ./package.json:/var/www/package.json

  express:
    image: node:latest
    user: node
    working_dir: /var/www
    command: npm -q start
    ports:
      - '8003:3000'
      - '3003:3001'
    volumes:
      - ./chat-express:/var/www
      - ./components:/var/www/components
      - ./package.json:/var/www/package.json
