version: '3'
services:
  node:
    image: node:latest
    user: node
    working_dir: /var/www
    command: npm -q start
    ports:
      - '8000:8000'
      - '8001:8001'
    volumes:
      - .:/var/www
